"""empty message

Revision ID: 2825e0249917
Revises: b71351b813fa
Create Date: 2018-09-25 13:56:47.797783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2825e0249917'
down_revision = 'b71351b813fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemedited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Boolean(), nullable=True),
    sa.Column('brand', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemedited_edited_timestamp'), 'itemedited', ['edited_timestamp'], unique=False)
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var_name', sa.String(length=120), nullable=False),
    sa.Column('sp', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variantedited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('var_name', sa.Boolean(), nullable=True),
    sa.Column('sp', sa.Boolean(), nullable=True),
    sa.Column('cp', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Boolean(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantedited_edited_timestamp'), 'variantedited', ['edited_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variantedited_edited_timestamp'), table_name='variantedited')
    op.drop_table('variantedited')
    op.drop_table('variant')
    op.drop_index(op.f('ix_itemedited_edited_timestamp'), table_name='itemedited')
    op.drop_table('itemedited')
    # ### end Alembic commands ###
