"""empty message

Revision ID: f8c039212bf7
Revises: ce595b8aa7bd
Create Date: 2018-09-25 23:22:48.623642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c039212bf7'
down_revision = 'ce595b8aa7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemedited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Boolean(), nullable=True),
    sa.Column('brand', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemedited_edited_timestamp'), 'itemedited', ['edited_timestamp'], unique=False)
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var_name', sa.String(length=120), nullable=False),
    sa.Column('sp', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variantedited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('var_name', sa.Boolean(), nullable=True),
    sa.Column('sp', sa.Boolean(), nullable=True),
    sa.Column('cp', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Boolean(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantedited_edited_timestamp'), 'variantedited', ['edited_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variantedited_edited_timestamp'), table_name='variantedited')
    op.drop_table('variantedited')
    op.drop_table('variant')
    op.drop_index(op.f('ix_itemedited_edited_timestamp'), table_name='itemedited')
    op.drop_table('itemedited')
    op.drop_table('user')
    op.drop_table('items')
    # ### end Alembic commands ###
